apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  selector:
    matchLabels:
      app: api
  replicas: 2
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: nestjs-template-api-api:latest
        imagePullPolicy: Never
        env:
        - name: DATABASES_MONGO_URL
          valueFrom:
            secretKeyRef:
              name: config
              key: databases-mongo-url
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: config
              key: node-env
        - name: APP_NAME
          valueFrom:
            configMapKeyRef:
              name: config
              key: app-name
        - name: BASE_URL
          valueFrom:
            configMapKeyRef:
              name: config
              key: base-url
        - name: API_PORT
          value: "3000"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  type: NodePort
  selector:
    app: api
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30100