apiVersion: v1
kind: Secret
metadata:
  name: config
type: Opaque
data:
  mongo-user: ZGV2
  mongo-password: dGVzdA==
  databases-mongo-url: bW9uZ29kYjovL2Rldjp0ZXN0QG1vbmdvZGI6MjcwMTcvbmVzdC10ZW1wbGF0ZT9hdXRoU291cmNlPWFkbWlu